name: Deploy Aurora Watch Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        cd lambda
        ls -l
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Lambda function
      run: |
        cd lambda
        zip -r ../function.zip .

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: |
        terraform init

    - name: Terraform Plan
      run: |
        terraform plan -out=tfplan -var="harvest_lambda_function_name=${{ secrets.LAMBDA_FUNCTION_NAME }}" -var="aws_region=${{ secrets.AWS_REGION }}" -var="sns_email_address=${{ secrets.SNS_EMAIL_ADDRESS }}"

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve tfplan  # Use the plan file created in the previous step

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --zip-file fileb://function.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

