name: Deploy Aurora Watch Lambda

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install global dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # For API Gateway test

    - name: Install and build harvest lambda
      run: |
        cd lambda
        pip install -r requirements.txt -t .
        zip -r ../harvest-function.zip .

    - name: Install and build service lambda
      run: |
        cd service
        pip install -r requirements.txt -t .
        zip -r ../service-function.zip .

    - name: Run unit tests
      run: |
        cd service
        python -m unittest test_lambda_function.py

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: |
        terraform init

    - name: Terraform Plan
      run: |
        terraform plan -out=tfplan -var="aws_region=${{ secrets.AWS_REGION }}" -var="sns_email_address=${{ secrets.SNS_EMAIL_ADDRESS }}"

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve tfplan

    - name: Terraform Output
      run: |
        terraform output

    - name: Run API Gateway test
      run: |
        python test_api_gateway.py
