name: Deploy Aurora Watch Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install harvest lambda dependencies
      run: |
        cd lambda
        ls -l
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build service lambda function
      run: |
        cd lambda
        zip -r ../harvest-function.zip .

    - name: Install service lambda dependencies
      run: |
        cd service
        ls -l
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Build service lambda function
      run: |
        cd service
        zip -r ../service-function.zip .    

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: |
        terraform init

    - name: Terraform Plan
      run: |
        terraform plan -out=tfplan -var="aws_region=${{ secrets.AWS_REGION }}" -var="sns_email_address=${{ secrets.SNS_EMAIL_ADDRESS }}"

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve tfplan  # Use the plan file created in the previous step


